name = "Kuvankaunis"
author = "SpaceGameDev Modding"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2b95b427373723777149c5629e5759f333235f2ae74036ddbc883b81973f8ad"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.11"]
