name = "Kuvankaunis"
author = "SpaceGameDev Modding"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65b3cab838b40836dc529dc9736a147369c1cf9ff3446b6cbd366b6480bc977f"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1.2"]
