#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Jul 18 19:00:45 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=Solas Shader V3.7.zip
